[package]
name = "actix-middleware-etag"
description = "ETag middleware for Actix web >= 4.1"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/chriswk/actix-middleware-etag"
homepage = "https://github.com/chriswk/actix-middleware-etag"
authors = ["Christopher Kolstad <git@chriswk.no>"]
license = "MIT"

[dependencies]
actix-service = "2.0.2"
actix-web =  "4.2.1"
base64 = "0.13.0"
futures = "0.3.24"
xxhash-rust = { version = "0.8.5", features =["xxh3"] }
